---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/auth/confirmation":
    post:
      summary: Resend confirmation
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: If your email address exists in our database, you will
                      receive an email with instructions for how to confirm your email
                      address in a few minutes
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                  required:
                  - email
    put:
      summary: Verify confirmation
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Your email address has been successfully confirmed
        '422':
          description: Failure
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unprocessable entity
                  status:
                    type: integer
                    example: 422
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        field:
                          type: string
                          example: confirmation_token
                        message:
                          type: string
                          example: Confirmation token is invalid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    confirmation_token:
                      type: string
                  required:
                  - confirmation_token
  "/api/v1/auth/password":
    post:
      summary: Request reset password
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: If your email address exists in our database, you will
                      receive a password recovery link at your email address in a
                      few minutes.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                  required:
                  - email
    put:
      summary: Change password
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Your password has been changed successfully
        '422':
          description: Failure
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unprocessable entity
                  status:
                    type: integer
                    example: 422
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        field:
                          type: string
                          example: reset_password_token
                        message:
                          type: string
                          example: Reset password token is invalid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    password:
                      type: string
                    reset_password_token:
                      type: string
                  required:
                  - password
                  - reset_password_token
  "/api/v1/auth/profile":
    get:
      summary: Get authenticated user
      tags:
      - Profile
      security:
      - bearer_auth: {}
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  email:
                    type: string
                    format: email
                  first_name:
                    type: string
                  last_name:
                    type: string
                  avatar_url:
                    type: string
                    format: uri
                    nullable: true
  "/api/v1/auth/profile/general":
    put:
      summary: Update user info
      tags:
      - Profile
      security:
      - bearer_auth: {}
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  email:
                    type: string
                    format: email
                  first_name:
                    type: string
                  last_name:
                    type: string
                  avatar_url:
                    type: string
                    format: uri
                    nullable: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    first_name:
                      type: string
                    last_name:
                      type: string
                    avatar:
                      type: string
                      example: blob_signed_id
                    current_password:
                      type: string
                  required:
                  - current_password
  "/api/v1/auth/profile/email":
    put:
      summary: Update user email
      tags:
      - Profile
      security:
      - bearer_auth: {}
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                    current_password:
                      type: string
                  required:
                  - email
                  - current_password
  "/api/v1/auth/profile/password":
    put:
      summary: Update user password
      tags:
      - Profile
      security:
      - bearer_auth: {}
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    password:
                      type: string
                    current_password:
                      type: string
                  required:
                  - password
                  - current_password
  "/api/v1/auth/sign_up":
    post:
      summary: Register user
      tags:
      - Authentication
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  email:
                    type: string
                    format: email
                  first_name:
                    type: string
                  last_name:
                    type: string
                  avatar_url:
                    type: string
                    nullable: true
        '422':
          description: Failure
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unprocessable entity
                  status:
                    type: integer
                    example: 422
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        field:
                          type: string
                          example: first_name
                        message:
                          type: string
                          example: First name can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                    password:
                      type: string
                    first_name:
                      type: string
                    last_name:
                      type: string
                  required:
                  - email
                  - password
                  - first_name
                  - last_name
  "/api/v1/auth/sign_in":
    post:
      summary: Sign in user
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: Success
          headers:
            Authorization:
              schema:
                type: string
                example: Bearer YOUR_TOKEN_HERE
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  email:
                    type: string
                    format: email
                  first_name:
                    type: string
                  last_name:
                    type: string
                  avatar_url:
                    type: string
                    nullable: true
        '401':
          description: Failure
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid email or password
                  status:
                    type: integer
                    example: 401
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                    password:
                      type: string
                  required:
                  - email
                  - password
  "/api/v1/auth/sign_out":
    delete:
      summary: Sign out user
      tags:
      - Authentication
      security:
      - bearer_auth: {}
      responses:
        '204':
          description: Success
  "/api/v1/uploads":
    post:
      summary: Upload file
      tags:
      - Blobs
      security:
      - bearer_auth: {}
      parameters: []
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  signed_id:
                    type: string
                    example: eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaWxqWWpRM09UaGxZeTFsTlRnMUxUUTVZakF0WVRobFl5MW1PRE15WkdRMU9ESmlNVGNHT2daRlZBPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--2818ad28efa9dfee79453b700aaa73f57228fbe1
                  byte_size:
                    type: integer
                    example: 1024
                  content_type:
                    type: string
                    example: image/png
                  created_at:
                    type: integer
                    example: 1698039633
                  filename:
                    type: string
                    example: image.png
                  url:
                    type: string
                    format: uri
                    example: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaWxqWWpRM09UaGxZeTFsTlRnMUxUUTVZakF0WVRobFl5MW1PRE15WkdRMU9ESmlNVGNHT2daRlZBPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--2818ad28efa9dfee79453b700aaa73f57228fbe1/image.png
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: file
              required:
              - file
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
